// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prqzcsajwpipfeqnqhlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycXpjc2Fqd3BpcGZlcW5xaGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDExNjksImV4cCI6MjA2NzU3NzE2OX0.vb18DnFwvqxCxVIF32FDsB8jY5sJ8iOZEEtrgNELGQQ";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); 